Projrct2EventManagement/Models/Customer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projrct2EventManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        { }
        public  Customer(string customerName, string userName, string customerEmail, string password)
        {
            CustomerName = customerName;
            UserName = userName;
            CustomerEmail = customerName;
            Password = password;
        }
        public string CustomerName { get; set; }
        public string UserName { get; set; }
        public string CustomerEmail { get; set; }
        public string Password { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}

Projrct2EventManagement/Models/Feedback.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projrct2EventManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public string UserName { get; set; }
        public string Emailid { get; set; }
        public string CustomerFeedback { get; set; }
        public string Name { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}

Projrct2EventManagement/Controllers/CustomerController.cs
using Projrct2EventManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Projrct2EventManagement.Controllers
{
    public class CustomerController : Controller
    {
        ProjectEventManagementEntities1 db = new ProjectEventManagementEntities1();
        // GET: Customer
        public ActionResult CustomerNavigate()
        {
            return View();
        }
        public ActionResult ViewEventsList()
        {
            ProjectEventManagementEntities1 db = new ProjectEventManagementEntities1();


            var image = db.EventsAndDecorations;
            return View(image);



        }


        //public ActionResult ViewOrderDetails()
        //{
        //   int  = TempData.Peek("EventType").ToString();
        //    var data = db.Orders.Where(d => d. Event== EventType);
        //    return View(data);
        //}
        public ActionResult PlaceOrder()
        {
            return View();
        }
        [HttpPost]
        public ActionResult PlaceOrder(Order orders)
        {
            using (var context = new ProjectEventManagementEntities1())
            {
                db.Orders.Add(orders);
                db.SaveChanges();


            }
            string message = "Order placed successfully";
            ViewBag.Message = message;
            return View();



        }
        public ActionResult OrderDetailsView()
        {

            ProjectEventManagementEntities1 db = new ProjectEventManagementEntities1();
            var list = db.Orders.ToList();
            return View(list);
        }

        public ActionResult Index()
        {
            return View(db.Feedbacks.ToList());
        }
       
    }


}


    

Projrct2EventManagement/Controllers/FeedbacksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Projrct2EventManagement.Models;

namespace Projrct2EventManagement.Controllers
{
    public class FeedbacksController : Controller
    {
        private ProjectEventManagementEntities1 db = new ProjectEventManagementEntities1();

        // GET: Feedbacks
        public ActionResult Index()
        {
            var feedbacks = db.Feedbacks.Include(f => f.UserDetail);
            return View(feedbacks.ToList());
        }

        // GET: Feedbacks/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Feedback feedback = db.Feedbacks.Find(id);
            if (feedback == null)
            {
                return HttpNotFound();
            }
            return View(feedback);
        }

        // GET: Feedbacks/Create
        public ActionResult Create()
        {
            ViewBag.UserName = new SelectList(db.UserDetails, "UserName", "Name");
            return View();
        }

        // POST: Feedbacks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserName,Emailid,CustomerFeedback,Name")] Feedback feedback)
        {
            if (ModelState.IsValid)
            {
                db.Feedbacks.Add(feedback);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserName = new SelectList(db.UserDetails, "UserName", "Name", feedback.UserName);
            return View(feedback);
        }

        // GET: Feedbacks/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Feedback feedback = db.Feedbacks.Find(id);
            if (feedback == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserName = new SelectList(db.UserDetails, "UserName", "Name", feedback.UserName);
            return View(feedback);
        }

        // POST: Feedbacks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserName,Emailid,CustomerFeedback,Name")] Feedback feedback)
        {
            if (ModelState.IsValid)
            {
                db.Entry(feedback).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserName = new SelectList(db.UserDetails, "UserName", "Name", feedback.UserName);
            return View(feedback);
        }

        // GET: Feedbacks/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Feedback feedback = db.Feedbacks.Find(id);
            if (feedback == null)
            {
                return HttpNotFound();
            }
            return View(feedback);
        }

        // POST: Feedbacks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Feedback feedback = db.Feedbacks.Find(id);
            db.Feedbacks.Remove(feedback);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Projrct2EventManagement/Controllers/UserDetailsController.cs
using Projrct2EventManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projrct2EventManagement.Controllers
{
    public class UserDetailsController : Controller
    {
        ProjectEventManagementEntities1 db = new ProjectEventManagementEntities1();
        // GET: UserDetails
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(UserDetail userDetail)
        {

            db.UserDetails.Add(userDetail);
            db.SaveChanges();
            var user = db.UserDetails.Single(u => u.UserName == userDetail.UserName);
            if (user.Role == "EventManager")
            {
                EventManager eventManager = new EventManager(user.Name, user.Email, user.Password, user.UserName);
                db.EventManagers.Add(eventManager);
                db.SaveChanges();
            }
            if (user.Role == "Customer")
            {
                Customer customer = new Customer(user.Name, user.UserName, user.Email, user.Password);
                db.Customers.Add(customer);
                db.SaveChanges();
            }
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(UserDetail userDetail)
        {
            try
            {
                UserDetail ud = db.UserDetails.Single(x => userDetail.UserName == userDetail.UserName && x.Name==userDetail.Name && x.Password == userDetail.Password && x.Role == userDetail.Role && x.Email == userDetail.Email);
                if (ud != null)
                {
                    if (ud.Role == "EventManager")

                    {

                        return RedirectToAction("ManagerNavigate", "EventManager");
                    }
                    if (ud.Role == "Customer")

                    {

                        return RedirectToAction("CustomerNavigate", "Customer");
                    }
                }
            }
            catch
            {
                ViewBag.Message = "User not found... Please enter correct details";
            }
            return View();


        }

    }
}

Projrct2EventManagement/Views/Customer/CustomerNavigate.cshtml
<<html>
<head>
    <style>
        body {
            
          text-align:center;
        }
    </style>
</head>
<body>
    <link href="~/Content/NavigateStyle.css" rel="stylesheet" />
    <div class="navigateBox">
        <h1 id="heading">Welcome To Customer Page</h1>"
        <h2 id="heading">Menu</h2>
        <p id="firstline">Please select an option :</p>
        <nav>
            <div class="actionLinkClass">
                <p></p>
                @Html.ActionLink("View List of events and Decoration", "ViewEventsList")
            </div>
            <div class="actionLinkClass">
                <p></p>
                @Html.ActionLink("Place Order", "PlaceOrder")

            </div>

            <div class="actionLinkClass">
                <p></p>
                @Html.ActionLink("View Order Details", "OrderDetailsView")
            </div>


            <div class="actionLinkClass">
                <p></p>
                @Html.ActionLink("Drop Your FeedBack", "Index","Feedbacks")
            </div>

        </nav>
    </div>
    <br/>
    <div>
        @Html.ActionLink("Logout", "Login", "UserDetails")
    </div>
</body>
</html>

Projrct2EventManagement/Views/Customer/FeedBack.cshtml
@model IEnumerable<Projrct2EventManagement.Models.Feedback>

@{
    ViewBag.Title = "FeedBack";
}

<h2>FeedBack</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Emailid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CustomerFeedback)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Emailid)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerFeedback)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
      
    </tr>
}

</table>
<div>
    @Html.ActionLink("Back to menu", "CustomerNavigate", "Customer")
</div>

Projrct2EventManagement/Views/Customer/OrderDetailsView.cshtml
@model IEnumerable<Projrct2EventManagement.Models.Order>

@{
    ViewBag.Title = "OrderDetailsView";
}

<h2>OrderDetailsView</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EventId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EventId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderDate)
        </td>
       </tr>
}

</table>
<div>
    @Html.ActionLink("Back to menu", "CustomerNavigate", "Customer")
</div>

Projrct2EventManagement/Views/Customer/PlaceOrder.cshtml
@model Projrct2EventManagement.Models.Order

@{
    ViewBag.Title = "PlaceOrder";
}

<h2>PlaceOrder</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Order</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.OrderId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OrderId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OrderId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.EventId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EventId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EventId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OrderDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OrderDate, new { htmlAttributes = new { type = "Date", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OrderDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to menu", "CustomerNavigate","Customer")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Projrct2EventManagement/Views/Customer/ViewEventsList.cshtml
@model IEnumerable<Projrct2EventManagement.Models.EventsAndDecoration>

@{
    ViewBag.Title = "ViewEventsList";
}

<h2>ViewEventsList</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EventType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DecorationType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DecorationImage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EventType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DecorationType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DecorationImage)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
           
        </tr>
    }

</table>
<div>
    @Html.ActionLink("Back to Menu", "CustomerNavigate", "Customer")
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Projrct2EventManagement/Views/Customer/ViewOrderDetails.cshtml
@model IEnumerable<Projrct2EventManagement.Models.Order>

@{
    ViewBag.Title = "ViewOrderDetails";
}

<h2>ViewOrderDetails</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EventId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EventId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.OrderId }) |
            @Html.ActionLink("Details", "Details", new { id=item.OrderId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.OrderId })
        </td>
    </tr>
}

</table>